#pragma once

#include <cstdint>


enum class AsciiStyleCode : uint8_t {
    Normal = 0,
    Bold = 1,
    Faint = 2,
    Italic = 3,
    Underline = 4,
    Blink = 5,
    RapidBlink = 6,
    Reverse = 7,
    ConcealOrHide = 8,
    Strike = 9,
    Primary = 10,
    AltenativeFontStart = 11,
    AltenativeFontEnd = 19,
    Gothic = 20,
    StartInverse = 21,
    DoubleUnderlineOrNotBold = 21,
    NotFaint = 22,
    NotItalic = 23,
    NotUnderline = 24,
    NotBlinking = 25,
    ProportionalSpacing = 26,
    NotReversed = 27,
    Reveral = 28,
    NotStrike = 29,
    EndInverse = 29,
    Foregrount4StartLower = 30,
    Foreground8Or24 = 38,
    ResetForeground = 39,
    Background4StartLower = 40,
    Background8Or24 = 48,
    ResetBackground = 49,
    NotProportionalSpacing = 50,
    Framed = 51,
    Encirled = 52,
    Overlined = 53,
    NotFramedNotEncircled = 54,
    NotOverlined = 55,
    UnderlineColor = 58,
    ResetUnderlineColor = 59,
    IdeogramUnderline = 60,
    IdeogramDoubleUnderline = 61,
    IdeogramOverline = 62,
    IdeogramDoubleOverline = 63,
    IdeogramSterssMarking = 64,
    NotIdeogram = 65,
    Superscript = 73,
    Subscript = 74,
    NotSuperSubScript = 75,
    Foregrount4StartUpper = 90,
    Background4StartUpper = 100,
};
